web:
  image: "nginx:latest"
  ports:
    - "8000:80"
  links:
    - db
    - php
  volumes:
    - ./code:/code
    - ./site.conf:/etc/nginx/conf.d/default.conf
php:
  image: php:7-fpm
  links:
    - db
  volumes:
    - ./code:/code
db:
  image: "mysql:5"
  volumes:
    - ./mysql.d:/etc/mysql/conf.d
    - ./mysql/data:/var/lib/mysql
  environment:
    MYSQL_ROOT_PASSWORD: phpapptest
    MYSQL_DATABASE: phpapp
